name: New Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      NAME: Simoncio

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

      - name: Hola Mundo
        run: echo "Hola Mundo $NAME"
  
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"

      - name: Hola Mundo 2
        run: echo "$SALIDA"

  third_job:
    runs-on: ubuntu-latest

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after actions
        run: ls -al